kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-1-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-1-pv
